// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'button': string;
  'menu': string;
  'mod': string;
  'wrapper': string;
}
export const cssExports: CssExports;
export default cssExports;
