// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'description': string;
  'details': string;
  'plugStats': string;
  'pointyBit': string;
  'popup': string;
  'stats': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
