// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'fourSections': string;
  'mods': string;
  'oneSection': string;
}
export const cssExports: CssExports;
export default cssExports;
