// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'arcSection': string;
  'fourSections': string;
  'header': string;
  'mods': string;
  'oneSection': string;
  'solarSection': string;
  'subSection': string;
  'subheader': string;
  'voidSection': string;
}
export const cssExports: CssExports;
export default cssExports;
